name: Deploy To Staging
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - docs/**
concurrency:
  group: deploy-staging
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - run: echo "STAGING deploy ref=$GITHUB_REF sha=$GITHUB_SHA"
