name: Unit Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "UNIT base=$GITHUB_BASE_REF"
