name: Log Shipper Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - observability/**
jobs:
  test-logshipper:
    runs-on: ubuntu-latest
    steps:
      - run: echo "LOGSHIPPER tests base=$GITHUB_BASE_REF"
